services:
  - type: web
    name: semantic-search-app
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=$PORT
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
    plan: free
